spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: saas_user
    password: saas_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

server:
  port: 8086

security:
  jwt:
    private-key-path: ${JWT_PRIVATE_KEY_PATH}
    expiration-seconds: 900

services:
  customer-service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
