spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5437/transaction_db
    username: saas_user
    password: saas_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt-public.pem

server:
  port: 8087

services:
  account:
    base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health


springdoc:
  swagger-ui:
    path: /swagger-ui.html