spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: accountuser
    password: accountpassword

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt-public.pem

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health